academic_data/urls.py
from django.urls import path, include

from .views import (
  SectionView,
  GradeView,
  SubjectView,
  AcademicPeriodView,
  TeacherListView,
  TeacherCreateView,
  TeacherUpdateView,
  delete_teacher,
  TuitionListView,
  TuitionDetailView,
  TuitionCreateView,
  TuitionUpdateView,
  delete_tuition,
  upload_qualification_by_student,
  upload_qualification_by_tuition,
  tuition_detail_api,
  export_pdf,
  report_html,
  report_constancia,
)

urlpatterns = [
  path("sections/", SectionView.as_view(), name="sections"),
  path("sections/<int:section_id>/", SectionView.as_view(), name="section"),
  path("grades/", GradeView.as_view(), name="grades"),
  path("grades/<int:grade_id>/", GradeView.as_view(), name="grade"),
  path("subjects/", SubjectView.as_view(), name="subjects"),
  path("subjects/<int:subject_id>/", SubjectView.as_view(), name="subject"),
  path("academic-periods/", AcademicPeriodView.as_view(), name="academic-periods"),
  path("academic-periods/<int:academic_period_id>/", AcademicPeriodView.as_view(), name="academic-period"),
  path("teachers/", TeacherListView.as_view(), name="teachers-list"),
  path("teachers/create/", TeacherCreateView.as_view(), name="create-teacher"),
  path("teacher/update/<int:teacher_id>/", TeacherUpdateView.as_view(), name="update-teacher"),
  path("teacher/delete/<int:teacher_id>/", delete_teacher, name="delete-teacher"),
  path("tuitions/", TuitionListView.as_view(), name="tuitions-list"),
  path("tuitions/<int:tuition_id>/", TuitionDetailView.as_view(), name="detail-tuition"),
  path("tuitions/create/", TuitionCreateView.as_view(), name="create-tuition"),
  path("tuition/update/<int:tuition_id>/", TuitionUpdateView.as_view(), name="update-tuition"),
  path("tuition/delete/<int:tuition_id>/", delete_tuition, name="delete-tuition"),
  path("qualification/upload-qualification-by-student/", upload_qualification_by_student, name="upload-qualification-by-student"),
  path("qualification/upload-qualification-by-tuition/", upload_qualification_by_tuition, name="upload-qualification-by-tuition"),
  path("api/tuition_detail_api/<int:tuition_id>/<int:subject_id>/<int:moment_id>/", tuition_detail_api, name="tuition_detail_api"),
  path("tuitions/report/<int:tuition_id>/<int:student_id>/", export_pdf, name="detail-tuition-report"),
  path("tuitions/report/html/<int:student_id>/", report_html, name="detail-tuition-report-htyml"),
  path("tuitions/proof/<int:student_id>/", report_constancia, name="proof-studies"),
]

audit/urls.py
from django.urls import path

from .views import (
  AuditListView,
)

urlpatterns = [
  path("audit_records/", AuditListView.as_view(), name="audit"),
]

edoardo_crema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("select2/", include("django_select2.urls")),
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("", include("common.urls")),
    path("academic-data/", include("academic_data.urls")),
    path("", include("students.urls")),
    path("", include("audit.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        # ...
    ] + urlpatterns

academic_data/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from bulk_update_or_create import BulkUpdateOrCreateQuerySet

from common.models import TimeStamp, Parish, Gender, Shift, Moment
from students.models import Student


class Subject(TimeStamp):
    name = models.CharField(max_length=50, verbose_name="nombre")

    class Meta:
        verbose_name = "materia"
        verbose_name_plural = "materias"
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Teacher(TimeStamp):
    class Status(models.TextChoices):
        ACTIVE = "active", _("activo")
        INACTIVE = "inactive", _("inactivo")

    first_name = models.CharField(max_length=50, verbose_name="primer nombre")
    second_name = models.CharField(
        max_length=50, verbose_name="segundo nombre", null=True, blank=True
    )
    first_surname = models.CharField(max_length=50, verbose_name="primer apellido")
    second_surname = models.CharField(
        max_length=50, verbose_name="segundo apellido", null=True, blank=True
    )
    birthday_date = models.DateField(verbose_name="fecha de nacimiento", null=True)
    identity_card = models.CharField(max_length=10, verbose_name="cedula de identidad", unique=True)
    gender = models.ForeignKey(Gender, models.PROTECT, verbose_name="genero", related_name="teachers", null=True)
    email = models.EmailField(verbose_name="correo electronico", null=True, blank=True)
    phone_number = models.CharField(
        max_length=15, verbose_name="numero de telefono", null=True, blank=True
    )
    address = models.CharField(max_length=200, verbose_name="direccion")
    parish = models.ForeignKey(Parish, models.SET_NULL, null=True, verbose_name="parroquia")
    subjects = models.ManyToManyField(Subject, verbose_name="materias")
    start_date = models.DateField(verbose_name="fecha de inicio", null=True)
    status = models.CharField(max_length=10, verbose_name="estatus", choices=Status.choices, default=Status.ACTIVE)

    class Meta:
        verbose_name = "docente"
        verbose_name_plural = "docentes"

    def __str__(self):
        return f"{self.first_name} {self.first_surname}"


class Section(TimeStamp):
    group = models.CharField(max_length=1, verbose_name="grupo", unique=True)

    class Meta:
        verbose_name = "seccion"
        verbose_name_plural = "secciones"
        ordering = ["group"]

    def __str__(self):
        return self.group


class Grade(TimeStamp):
    year = models.CharField(max_length=3, verbose_name="año", unique=True)
    subjects = models.ManyToManyField(Subject, verbose_name="materias")

    class Meta:
        verbose_name = "grado"
        verbose_name_plural = "grados"
        ordering = ["year"]
    
    def __str__(self):
        return self.year


class AcademicPeriod(TimeStamp):
    period = models.CharField(max_length=9, verbose_name="periodo", unique=True)

    class Meta:
        verbose_name = "periodo academico"
        verbose_name_plural = "periodos academicos"
    
    def __str__(self):
        return self.period


class Tuition(TimeStamp):
    academic_period = models.ForeignKey(AcademicPeriod, models.CASCADE, verbose_name="periodo academico")
    grade = models.ForeignKey(Grade, models.CASCADE, verbose_name="grado")
    section = models.ForeignKey(Section, models.CASCADE, verbose_name="seccion")
    shift = models.ForeignKey(Shift, models.PROTECT, verbose_name="turno")
    students = models.ManyToManyField(Student, verbose_name="estudiantes", blank=True)

    class Meta:
        verbose_name = "matricula"
        verbose_name_plural = "matriculas"
        default_related_name = "tuitions"
        unique_together = ["academic_period", "grade", "section"]

    def __str__(self):
        return f"{self.academic_period} - {self.grade} {self.section}"


class Qualification(TimeStamp):
    objects = BulkUpdateOrCreateQuerySet.as_manager()

    student = models.ForeignKey(Student, models.CASCADE, verbose_name="estudiante")
    tuition = models.ForeignKey(Tuition, models.CASCADE, verbose_name="matricula")
    subject = models.ForeignKey(Subject, models.CASCADE, verbose_name="materia")
    moment = models.ForeignKey(Moment, models.CASCADE, verbose_name="momento", default=None)
    note = models.DecimalField(verbose_name="nota", max_digits=3, decimal_places=1, default=0.0)

    class Meta:
        verbose_name = "calificacion"
        verbose_name_plural = "calificaciones"
        default_related_name = "qualifications"

    def __str__(self):
        return f"{self.student.full_name} - {self.subject.name} - {self.note}"


class AllNotes(models.Model):
    student_id = models.IntegerField(primary_key=True, verbose_name="estudiante")
    matricula = models.IntegerField(verbose_name="matricula")
    cedula = models.CharField(max_length=50, verbose_name="cedula")
    p_nombre = models.CharField(max_length=50, verbose_name="p_nombre")
    s_nombre = models.CharField(max_length=50, verbose_name="s_nombre")
    p_apellido = models.CharField(max_length=50, verbose_name="p_apellido")
    s_apellido = models.CharField(max_length=50, verbose_name="s_apellido")
    grado = models.CharField(max_length=50, verbose_name="grado")
    seccion = models.CharField(max_length=50, verbose_name="seccion")
    turno = models.CharField(max_length=50, verbose_name="turno")
    momento1 = models.CharField(max_length=50, verbose_name="momento1")
    momento2 = models.CharField(max_length=50, verbose_name="momento2")
    momento3 = models.CharField(max_length=50, verbose_name="momento3")
    definitiva = models.CharField(max_length=50, verbose_name="definitiva")
    asignacion = models.CharField(max_length=50, verbose_name="asignacion")
    #nota = models.CharField(max_length=50, verbose_name="nota")
    periodo = models.CharField(max_length=50, verbose_name="period")

    class Meta:
        db_table = "academic_notes_all"
        managed = False

common/models.py
from django.db import models

from django_softdelete.models import SoftDeleteModel


# Create your models here.
class TimeStamp(SoftDeleteModel, models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Country(TimeStamp):
    name = models.CharField(max_length=50, verbose_name="nombre")

    class Meta:
        verbose_name = "pais"
        verbose_name_plural = "paises"

    def __str__(self) -> str:
        return f"{self.name}"


class State(TimeStamp):
    name = models.CharField(max_length=50, verbose_name="nombre")
    capital = models.CharField(max_length=50, verbose_name="capital", null=True)
    country = models.ForeignKey(
        Country, on_delete=models.PROTECT, related_name="states", verbose_name="pais"
    )

    class Meta:
        verbose_name = "estado"
        verbose_name_plural = "estados"

    def __str__(self) -> str:
        return f"{self.name} - {self.capital}"


class Municipality(TimeStamp):
    name = models.CharField(max_length=50, verbose_name="nombre")
    state = models.ForeignKey(
        State,
        on_delete=models.PROTECT,
        related_name="municipalities",
        verbose_name="estado",
    )

    class Meta:
        verbose_name = "municipio"
        verbose_name_plural = "municipios"

    def __str__(self) -> str:
        return f"{self.name}"


class Parish(TimeStamp):
    name = models.CharField(max_length=50, verbose_name="nombre")
    municipality = models.ForeignKey(
        Municipality,
        on_delete=models.PROTECT,
        related_name="parishes",
        verbose_name="municipio",
    )

    class Meta:
        verbose_name = "parroquia"
        verbose_name_plural = "parroquias"

    def __str__(self) -> str:
        return f"{self.name}"


class Gender(models.Model):
    name = models.CharField(max_length=20, verbose_name="nombre")

    class Meta:
        verbose_name = "genero"
        verbose_name_plural = "generos"

    def __str__(self):
        return f"{self.name}"


class Shift(SoftDeleteModel, models.Model):
    turn = models.CharField(max_length=20, verbose_name="turno")

    class Meta:
        verbose_name = "jornada de estudio"
        verbose_name_plural = "jornadas de estudio"
    
    def __str__(self):
        return f"{self.turn}"


class Moment(models.Model):
    number = models.CharField(max_length=3, verbose_name="numero de momento")

    class Meta:
        verbose_name = "momento"
        verbose_name_plural = "momentos"
    
    def __str__(self):
        return f"{self.number} momento"

academic_data/templates/academic_data/teachers/create_teacher.html
{% extends "common/base.html" %}
{% load bootstrap_icons %}
{% load crispy_forms_tags %}

{% block content %}
  <form class="p-3 border border-primary rounded needs-validation" action="/academic-data/teachers/create/" method="POST" id="form" novalidate>
    {% csrf_token %}
    <div>
      <div class="form-group">
        {{ form | crispy }}
      </div>
      <div>
        <label for="id_country" class="form-label">Pais</label>
        <select name="country" id="" class="select form-select" id="id_country">
          <option value="">Seleccionar</option>
        </select>
      </div>
    </div>

    <hr size="10" class="mt-5">

    <div class="d-flex justify-content-end">
        <button class="btn btn-primary mr-auto" type="submit">Guardar</button>
    </div>
  </form>
{% endblock content %}

academic_data/templates/academic_data/teachers/form_teacher.html
{% extends "common/base.html" %}
{% load bootstrap_icons %}
{% load crispy_forms_tags %}

{% block content %}
  <form class="p-3 border border-primary rounded needs-validation" action="{{ form_action }}" method="POST" id="form" novalidate>
    {% csrf_token %}
    <div>
      <div class="form-group">
        {{ form | crispy }}
      </div>
      <div>
        <label for="id_country" class="form-label">Pais</label>
        <select name="country" id="" class="select form-select" id="id_country">
          <option value="">Seleccionar</option>
        </select>
      </div>
    </div>

    <hr size="10" class="mt-5">

    <div class="d-flex justify-content-end">
        <button class="btn btn-primary mr-auto" type="submit">Guardar</button>
    </div>
  </form>
{% endblock content %}

academic_data/templates/academic_data/teachers/teacher_form.html
{% extends "common/base.html" %}
{% load bootstrap_icons %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="card div-glass mt-3">
    <div class="card-header div-glass-blue">
      <h2 class="text-center text-box">{{ action }} DOCENTE</h2>
    </div>
    <div class="card-body">
      <form class="p-3  is-invalid" action="{{ form_action }}" method="POST" id="form" novalidate>
        {% csrf_token %}
        <div>
            <h3 class="text-box">Datos Filiatorios</h3>
            <div class="form-group">
              <div class="row">
                <div class="col-6">
                  {{ form.first_name|as_crispy_field }}
                </div>
                <div class="col-6">
                  {{ form.second_name|as_crispy_field }}
                </div>
              </div>
              <div class="row">
                <div class="col-6">
                  {{ form.first_surname|as_crispy_field }}
                </div>
                <div class="col-6">
                  {{ form.second_surname|as_crispy_field }}
                </div>
              </div>
              <div class="row">
                <div class="col-6">
                  {{ form.identity_card|as_crispy_field }}
                </div>
                <div class="col-3">
                  {{ form.birthday_date|as_crispy_field }}
                </div>
                <div class="col-3">
                  {{ form.start_date|as_crispy_field }}
                </div>
              </div>
              <div class="row">
                <div class="col-6">
                  {{ form.subjects|as_crispy_field }}
                </div>
                <div class="col-3">
                  {{ form.status|as_crispy_field }}
                </div>
                <div class="col-3">
                  {{ form.gender|as_crispy_field }}
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-3">
                  <label for="id_country" class="form-label">Pais</label>
                  <select name="country" class="select form-select" id="id_country" onchange="handleChangeCountry(event)">
                    <option value="" selected>Seleccionar</option>
                    {% for country in countries %}
                      <option value="{{ country.id }}">{{ country.name }}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col-2">
                  <div class="mb-3">
                    <label for="id_state" class="form-label">Estado</label>
                    <select name="state" class="select form-select" id="id_state" onChange="handleChangeState(event)" disabled>
                      <option value="" selected>Seleccionar</option>
                    </select>
                  </div>
                </div>
                <div class="col-2">
                  <div class="mb-3">
                    <label for="id_capital" class="form-label">Capital</label>
                    <select name="capital" class="select form-select" id="id_capital" disabled>
                      <option value=""  selected>Seleccionar</option>
                    </select>
                  </div>
                </div>
                <div class="col-2">
                  <div class="mb-3">
                    <label for="id_municipality" class="form-label">Municipio</label>
                    <select name="municipality" class="select form-select" id="id_municipality" onChange="handleChangeMunicipality(event)" disabled>
                      <option value="" selected>Seleccionar</option>
                    </select>
                  </div>
                </div>
                <div class="col-2">
                  <div>
                    <label for="id_parish" class="form-label">Parroquia</label>
                    <select name="parish" class="select form-select" id="id_parish" disabled>
                      <option value="" selected>Seleccionar</option>
                    </select>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  {{ form.address|as_crispy_field }}
                </div>
              </div>
            </div>
        </div>
        <hr size="10" class="mt-5">
        <div class="d-flex justify-content-end">
            <button class="btn btn-glass-blue text-box mr-auto" type="submit">Guardar</button>
        </div>
      </form>
    </div>
  </div>
  


  <script>
    console.log('hola')
    console.log('{{countries}}')
    function handleChangeCountry(event) {
      let country_id = event.target.value
      console.log(country_id)
      let endpoint = `/api/countries/${country_id}/`
      
      fetch(endpoint)
        .then(response => {
          if (!response.ok) {
            throw new Error('Error en la solicitud: ' + response.statusText);
          }
          return response.json();
        })
        .then(data => {
          let selectState = document.getElementById("id_state");
          selectState.disabled = false;
          selectState.innerHTML = "";

          let newOption = document.createElement("option");
          newOption.value = "";
          newOption.text = "Seleccionar";
          selectState.add(newOption);
          
          data.states.forEach(state => {
            let newOption = document.createElement("option");
            newOption.value = state.id;
            newOption.text = state.name;
            selectState.add(newOption);
          })
        })
        .catch(error => {
          console.log(error)
        })
    }

    function handleChangeState(event) {
      let state_id = event.target.value
      let endpoint = `/api/states/${state_id}/`
      
      fetch(endpoint)
        .then(response => {
          if (!response.ok) {
            throw new Error('Error en la solicitud: ' + response.statusText);
          }
          return response.json();
        })
        .then(data => {
          let selectCapital = document.getElementById("id_capital");
          selectCapital.disabled = false;
          selectCapital.innerHTML = "";
          
          let newOptionCapital = document.createElement("option")
          newOptionCapital.value = "";
          newOptionCapital.text = data.capital;
          selectCapital.add(newOptionCapital);
          
          let selectMunicipality = document.getElementById("id_municipality");
          selectMunicipality.disabled = false;
          selectMunicipality.innerHTML = "";
          
          let newOptionMunicipality = document.createElement("option");
          newOptionMunicipality.value = "";
          newOptionMunicipality.text = "Seleccionar";
          selectMunicipality.add(newOptionMunicipality);
          
          data.municipalities.forEach(municipality => {
            let newOptionMunicipality = document.createElement("option")
            newOptionMunicipality.value = municipality.id;
            newOptionMunicipality.text = municipality.name;
            selectMunicipality.add(newOptionMunicipality);
          })
        })
        .catch(error => {
          console.log(error)
        })
    }

    function handleChangeMunicipality(event) {
      let municipality_id = event.target.value;
      let endpoint = `/api/municipalities/${municipality_id}/`

      fetch(endpoint)
        .then(response => {
          if (!response.ok) {
            throw new Error('Error en la solicitud: ' + response.statusText);
          }
          return response.json();
        })
        .then(data => {
          let selectParish = document.getElementById("id_parish");
          selectParish.disabled = false;
          selectParish.innerHTML = "";
          
          let newOptionParish = document.createElement("option");
          newOptionParish.value = "";
          newOptionParish.text = "Seleccionar";
          selectParish.add(newOptionParish);
          
          data.parishes.forEach(parish => {
            let newOptionParish = document.createElement("option")
            newOptionParish.value = parish.id;
            newOptionParish.text = parish.name;
            selectParish.add(newOptionParish);
          })
        })
        .catch(error => {
          console.log(error)
        })
    }
  </script>
{% endblock content %}

academic_data/templates/academic_data/teachers/teachers_list.html
{% extends "common/base.html" %}
{% load bootstrap_icons %}

{% block content %}
<h2 class="text-center mt-3 mb-3 text-box">DOCENTES</h2>
<div  class="mt-3 shadow-div">
  <table class="table table-sm table-striped shadow-div">
    <thead class="bg-nav">
      <tr>
        <th>Primer Nombre</th>
        <th>Segundo Nombre</th>
        <th>Primer Apellido</th>
        <th>Segundo Apellido</th>
        <th>Genero</th>
        <th class="buton-right">
          <a
            href="{% url 'create-teacher' %}"
            type="button"
            class="text-dark btn btn-sm btn-success"
            >
            + Nuevo
          </a>
        </th>
      </tr>
    </thead>
    <tbody>
      {% for teacher in object_list %}
      <tr>
        <td>{{ teacher.first_name }}</td>
        <td>{{ teacher.second_name|default:"" }}</td>
        <td>{{ teacher.first_surname }}</td>
        <td>{{ teacher.second_surname|default:"" }}</td>
        <td>{{ teacher.gender }}</td>
        <td class="buton-right">
          <a
            type="button"
            class="btn btn-sm btn-info text-dark"
            href="{% url 'update-teacher' teacher_id=teacher.id %}"
          >
            Editar
          </a>
          <a
            type="button"
            class="btn btn-sm btn-danger text-dark"
            href="{% url 'delete-teacher' teacher_id=teacher.id %}"
          >
            Eliminar
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}